#!/bin/python3

import sys


grid = []
for grid_i in range(20):
    grid_t = [int(grid_temp) for grid_temp in input().strip().split(' ')]
    grid.append(grid_t)
mul=0
    #up 
for i in range(20):
    for j in range(20):
            
            #down
        if i<17:
            mat = grid[i][j]*grid[i+1][j]*grid[i+2][j]*grid[i+3][j]
            if mat>mul:
                mul=mat
            
            #left or left
        if j<17:
            mat = grid[i][j]*grid[i][j+1]*grid[i][j+2]*grid[i][j+3]
            if mat>mul:
                mul=mat
            
            #diagonal left --> right
        if i<17 and j<17:
            mat = grid[i][j]*grid[i+1][j+1]*grid[i+2][j+2]*grid[i+3][j+3]
            if mat>mul:
                mul=mat
            
            #diagonal right --> left
        if i>2 and j>2:
            mat = grid[i][j-3]*grid[i-1][j-2]*grid[i-2][j-1]*grid[i-3][j] 
            if mat>mul:
                mul=mat
    
print(mul)                
                
