#!/bin/python3

import sys
import math
def isPrime(n):
    if n == 1:
        return False
    if n == 2 or n == 3:
        return True
    if n % 2 == 0:
        return False
    s = int(math.sqrt(n))
    for i in range(3, s+1, 2):
        if n % i == 0:
            return False
    return True

n = 10**4
i = 2
primes = []
while len(primes) <= n:
    if isPrime(i):
        primes.append(i)
    i += 1

t = int(input())
for _ in range(t):
    n = int(input())
    print(primes[n-1])
    
            

            
   
